### ISSUE TITLE
모델 활용을 위한 DB 테이블 생성

### ISSUE THREAD

**Issue by choitaedong2** [ClustProject/WSAutoMLUser#5]
테이블 사용 목적
 - 예측 데이터 저장 및 조회

테이블 명칭:
컬럼:
데이터 형식

**Comment by 0-wook** [comment]
테이블 사용 목적

예측 데이터 저장 및 조회
테이블 명칭: automl.conzon_row
컬럼: 
 1) CONZON_IDX
 2) CONZON_ID
 3) CONZON_NAME
 4) CONZON_DATE
 5) CONZON_DATA
데이터 형식
 1) bigint
 2) varchar
 3) varchar
 4) Date
 5) LONGTEXT(json)
